const cron = require('node-cron');
const AutoAttendanceService = require('../services/AutoAttendanceService');

/**
 * Tarea programada para procesar asistencia automática
 */
class AutoAttendanceJob {
  
  constructor() {
    this.isRunning = false;
    this.lastRun = null;
    this.nextRun = null;
  }
  
  /**
   * Inicia la tarea programada
   */
  start() {
    console.log('🕐 Iniciando tarea programada de asistencia automática...');
    
    // Ejecutar todos los días a las 6:00 AM (hora del servidor)
    this.scheduledTask = cron.schedule('0 6 * * *', async () => {
      await this.runDailyAttendance();
    }, {
      scheduled: false,
      timezone: "America/Mexico_City"
    });
    
    // Ejecutar todos los días a las 6:00 PM para verificar registros del día
    this.verificationTask = cron.schedule('0 18 * * *', async () => {
      await this.verifyDailyAttendance();
    }, {
      scheduled: false,
      timezone: "America/Mexico_City"
    });
    
    this.scheduledTask.start();
    this.verificationTask.start();
    
    console.log('✅ Tarea programada iniciada correctamente');
    console.log('📅 Horarios: 6:00 AM (registro) y 6:00 PM (verificación)');
  }
  
  /**
   * Detiene la tarea programada
   */
  stop() {
    if (this.scheduledTask) {
      this.scheduledTask.stop();
    }
    if (this.verificationTask) {
      this.verificationTask.stop();
    }
    console.log('⏹️ Tarea programada detenida');
  }
  
  /**
   * Ejecuta el procesamiento diario de asistencia
   */
  async runDailyAttendance() {
    if (this.isRunning) {
      console.log('⚠️ Tarea de asistencia automática ya está ejecutándose, saltando...');
      return;
    }
    
    this.isRunning = true;
    this.lastRun = new Date();
    
    try {
      console.log('🚀 Iniciando procesamiento automático de asistencia...');
      
      const result = await AutoAttendanceService.processDailyAttendance();
      
      console.log('✅ Procesamiento automático completado:', {
        processed: result.processed,
        created: result.created,
        errors: result.errors,
        timestamp: this.lastRun.toISOString()
      });
      
      // Log detallado de resultados
      if (result.details && result.details.length > 0) {
        console.log('📊 Detalles del procesamiento:');
        result.details.forEach(detail => {
          console.log(`  - ${detail.employeeName}: ${detail.status} (${detail.action})`);
        });
      }
      
    } catch (error) {
      console.error('❌ Error en procesamiento automático de asistencia:', error);
    } finally {
      this.isRunning = false;
    }
  }
  
  /**
   * Verifica los registros de asistencia del día
   */
  async verifyDailyAttendance() {
    try {
      console.log('🔍 Verificando registros de asistencia del día...');
      
      const today = new Date().toISOString().split('T')[0];
      const stats = await AutoAttendanceService.getAutoAttendanceStats(today, today);
      
      console.log('📈 Estadísticas del día:', {
        date: today,
        totalRecords: stats.totalRecords,
        autoGenerated: stats.autoGeneratedRecords,
        manual: stats.manualRecords,
        autoPercentage: stats.autoPercentage.toFixed(2) + '%'
      });
      
    } catch (error) {
      console.error('❌ Error verificando asistencia del día:', error);
    }
  }
  
  /**
   * Ejecuta la tarea manualmente (para testing)
   */
  async runManually(date = null) {
    console.log('🔧 Ejecutando tarea manual de asistencia automática...');
    await this.runDailyAttendance();
  }
  
  /**
   * Obtiene el estado de la tarea programada
   */
  getStatus() {
    return {
      isRunning: this.isRunning,
      lastRun: this.lastRun,
      nextRun: this.nextRun,
      scheduled: this.scheduledTask ? this.scheduledTask.running : false,
      verification: this.verificationTask ? this.verificationTask.running : false
    };
  }
  
  /**
   * Procesa asistencia para un rango de fechas específico
   */
  async processDateRange(startDate, endDate) {
    try {
      console.log(`📅 Procesando asistencia del ${startDate} al ${endDate}...`);
      
      const result = await AutoAttendanceService.processDateRange(startDate, endDate);
      
      console.log('✅ Procesamiento de rango completado:', {
        totalDays: result.totalDays,
        processed: result.processed,
        created: result.created,
        errors: result.errors
      });
      
      return result;
      
    } catch (error) {
      console.error('❌ Error procesando rango de fechas:', error);
      throw error;
    }
  }
}

// Instancia singleton
const autoAttendanceJob = new AutoAttendanceJob();

module.exports = autoAttendanceJob;
